### ISSUE TITLE
Class breadcrumbs does not exist

### ISSUE THREAD

**Issue by angelside** [letrunghieu/laravel-dashboard#1]
I just try dashboard. I am not install breadcrumbs, because its seem to be optional on composer.json file. I think breadcrumbs control statement not working,  [layout.blade.php#L47](https://github.com/letrunghieu/laravel-dashboard/blob/master/views/layout.blade.php#L47)

For correct I simple try var_dump() my controller

```
var_dump( app('breadcrumbs') );
```

Same error

```
Class breadcrumbs does not exist
```

**Comment by letrunghieu** [comment]
Thank you, I updated this package. That error is fixed. You can `composer update` to get the `1.0.1` version.
