### ISSUE TITLE
Duplicate menu

### ISSUE THREAD

**Issue by amrography** [letrunghieu/laravel-dashboard#5]
Hi 

Once I updated to Laravel 5.3 and downloaded laravel-dashboard again I face this issue.

![screen shot 2016-09-19 at 3 02 28](https://cloud.githubusercontent.com/assets/9614340/18632979/6fababa8-7e7a-11e6-90fa-30869ae54248.png)

This is my dashboard link in middleware file:

```
protected function registerSidebarMenu(){
      $menu = App('laravel_dashboard')->getSidebarMenu();
      $menu->setLabel('Madny 18')
      ->addLink(trans('dashboard.menu.dashboard'), ['route' => 'dash'], ['before' => '<i class="fa fa-home"></i>'])
      ->addLink(trans('dashboard.menu.new'),['to' => 'dashboard/post/create'], ['before' => '<i class="fa fa-plus"></i>'])
      ->addLink(trans('dashboard.menu.draft'), ['to' => 'dashboard/posts/draft'], ['before' => '<i class="fa fa-pencil"></i>'])
      ->addLink(trans('dashboard.menu.pending'), ['to' => 'dashboard/posts/pending'], ['before' => '<i class="fa fa-pencil-square-o"></i>'])
      ->addLink(trans('dashboard.menu.published'), ['to' => 'dashboard/posts/published'], ['before' => '<i class="fa fa-clone"></i>'])
      ->addLink(trans('dashboard.menu.settings'), ['route' => 'dash.settings'], ['before' => '<i class="fa fa-sliders"></i>'])
      ->addLink(trans('dashboard.menu.logout'), ['to' => '/logout'], ['before' => '<i class="fa fa-sign-out"></i>']);
    }
```

But I am sure it's not inserted twice.. but duplicated when print out to HTML

**Comment by letrunghieu** [comment]
Hi @amrography 

I tested this package with your menus in Laravel 5.3 and the result is fine. I think the problem is the menu registration (`registerSidebarMenu`) is called twice in your code.

![laravel-dashboard](https://cloud.githubusercontent.com/assets/1145335/18870658/e6803340-84db-11e6-9464-9ecea77a3dbe.png)
